nextcloud-libraries/nextcloud-vite-config

lib/appConfig.ts
lib/baseConfig.ts

Apps are built for browsers, so we should always polyfill node modules.

fix(app): Polyfill node core modules by default when building apps

---

README.md
lib/appConfig.ts
lib/baseConfig.ts
lib/libConfig.ts
lib/plugins/ImportCSS.ts
package-lock.json
package.json

This way we do not require any DOM environment to be present.

Allow to properly include CSS in library builds by importing the CSS files

---

banner-template.txt
lib/appConfig.ts
lib/baseConfig.ts

Currently the license information is written as a comment with the files, which is non deterministic resulting in node tests failures for e.g. logreader CI.
This way we output a LICENSE.txt containing all required license information similar to how it is currently done by using webpack.
:heavy_plus_sign: Reduced JS bundle while still providing the licenses.

fix: Make license information for 3rd party modules deterministic

---

lib/libConfig.ts

When using css inlining and multiple output formats (e.g. esm and cjs) the assets order is not deterministic. This causes issues if the assets are named the same, e.g. if you have multiple "index" entry points the assets will be called index1, index2... So when not using hashes the last output format might override the assets with a changed order, causing the previous output formats to be invalid.

fix(lib): Include hash in assets name

---

__tests__/libconfig.spec.ts
lib/libConfig.ts
package-lock.json
package.json

Workaround for https://github.com/vitejs/vite/issues/14515

fix(lib): Make libconfig work when minification and css split is enabled

---

.gitignore
.reuse/dep5
__fixtures__/app_process_env/main.js
__tests__/__snapshots__/appconfig.spec.ts.snap
__tests__/appconfig.spec.ts
lib/baseConfig.ts

Removing `process.env` is only required for apps, as we now build apps not in lib mode it is removed automatically by vite.
Fixes testing issues when using vitest.

fix: Remove `define` of `process.env` from base config

---

lib/libConfig.ts

1. Use https://github.com/nextcloud/server/pull/40692 with the latest `@nextcloud/vue`
2. Run `npm test` (or better just `npx jest CalDavSetting` for a single test)
3. See `[Vue warn]: Failed to mount component: template or render function not defined`
By default, 
> Rollup assumes that the required value should be treated as the default export of the imported module, just like when importing CommonJS from an ES module context in NodeJS. This is different from the default behavior in many tools like Babel or TS.
As a result, when a CJS lib built with this config is used with such tooling, external dependencies are imported as an object with a default property.
```js
// Inside NcComponent.cjs
const icon = require('vue-material-design-icons/Icon.vue)
// Imports as
{
default: {
name: 'Icon', …
```

fix(libConfig): import default in CJS build

---

lib/appConfig.ts
package-lock.json
package.json

For apps the config will generate a vite app config, so vite will try to preload all modules imported directly by the entry point.
To do so we have to configure the base path where to import the modules from (this is different from normal import, as module preloading works by adding the modules with their source URL to the document, meaning for normal imports the base url is not required (browsers support the relative imports), but for module preloading it is).
We can not set one base url, as we do not know it (we do not know the webroot of an app on build time).
So we need to use the runtime feature (currently hidden behind a the experimental flag).

feat(appconfig): Add base path so module preloading works

---

__tests__/appconfig.spec.ts
__tests__/libconfig.spec.ts
lib/appConfig.ts
lib/baseConfig.ts
lib/libConfig.ts

`mergeConfigs` doesn't work for `build.rollupOptions.output[].assetFileNames()`:
- In the lib config it merges `output` arrays and results in both default and new `assetFileNames`, duplicating assets
- In the app config it just replaces `appConfig.ts` values, requiring to override all cases, not only one specific, or duplicate this config defaults.
This PR adds new option `assetFileNames` to manually merge custom `assetFileNames` with the default. If custom one returns `undefiend` (falsy), then the default one is used.
If a lib has styles and its entrypoint is `main.ts`, then styles are built to `main.css` and it is not possible to change.
---
@susnux If this options is fine, what do you think about adding the same for chunk file names to not more everything to one folder?

feat: add option to customize asset file names

---

__tests__/appconfig.spec.ts
lib/appConfig.ts

The docs said `false` but it was `true`

fix(appconfig): Fix the default value for inlining CSS

---

CHANGELOG.md
package-lock.json
package.json

[Full Changelog](https://github.com/nextcloud-libraries/nextcloud-vite-config/compare/v1.0.1...v1.1.0)
* feat: add option to customize asset file names [\#41](https://github.com/nextcloud-libraries/nextcloud-vite-config/pull/41) ([ShGKme](https://github.com/ShGKme))
* feat\(appconfig\): Add base path so module preloading works [\#43](https://github.com/nextcloud-libraries/nextcloud-vite-config/pull/43) ([susnux](https://github.com/susnux))
* fix\(appconfig\): Fix the default value for inlining CSS [\#42](https://github.com/nextcloud-libraries/nextcloud-vite-config/pull/42) ([susnux](https://github.com/susnux))
* chore(deps): Bump postcss from 8.4.24 to 8.4.31 [\#37](https://github.com/nextcloud-libraries/nextcloud-vite-config/pull/37)
* chore(deps-dev): Bump @types/node from 20.8.1 to …

chore: Release 1.1.0

---

lib/baseConfig.ts

This might lead to unexpected behavior, for example this will break some `@nextcloud/vue` components like `NcActionCheckbox`.
Because then if you use translation comments the text will be broken.
```html
<NcActionCheckbox>
{{ t('foo', 'bar') }}
</NcActionCheckbox>
```
This will not lead to a checkbox with the text *TRANSLATORS: Some context* as the first VNode is the comment. This is not expected behavior. Users should set this config flag manually if needed.

fix: Do not set vue's `comments` setting for dev builds

---

CHANGELOG.md
package-lock.json
package.json

[Full Changelog](https://github.com/nextcloud-libraries/nextcloud-vite-config/compare/v1.1.0...v1.1.1)
* fix(typing): fix typo in typing by [\#69](https://github.com/nextcloud-libraries/nextcloud-vite-config/pull/69) \([ShGKme](https://github.com/ShGKme)\)
* fix: typo in readme by [\#83](https://github.com/nextcloud-libraries/nextcloud-vite-config/pull/83) \([raimund-schluessler](https://github.com/raimund-schluessler)\)
* fix: Do not set vue's `comments` setting for dev builds by [\#84](https://github.com/nextcloud-libraries/nextcloud-vite-config/pull/84) \([susnux](https://github.com/susnux)\)
* Updated dependencies

chore: Prepare patch release 1.1.1

---

__tests__/__snapshots__/appconfig.spec.ts.snap
lib/appConfig.ts
lib/index.ts
lib/libConfig.ts
lib/plugins/EmptyJSDir.ts
package-lock.json
package.json
tsconfig.json

* Supersedes #85 
* Closes #82 
This is a minimal version of #85 without bundling

enh: Support vite v5

---

lib/plugins/ImportCSS.ts

* Resolves https://github.com/nextcloud-libraries/nextcloud-vue/issues/4901
We must use `generateBundle` as Vite removes "empty css chunks" (chunks that only import css) in its `generateBundle` hook and merged the `importedCss` property down to the really emitted chunks.
Otherwise we will loose CSS imports!
See this example of the NcMentionBubble on the comments tab, current master with 8.5.1 the "after" with 8.5.1 but compiled with this changes.
before | after
---|---

fix(css-plugin): Use `generateBundle` hook to prevent CSS imports from being lost

---

CHANGELOG.md
package-lock.json
package.json

[Full Changelog](https://github.com/nextcloud-libraries/nextcloud-vite-config/compare/v1.2.0...v1.2.1)
* fix(css-plugin): Use `generateBundle` hook to prevent CSS imports from being lost [\#112](https://github.com/nextcloud-libraries/nextcloud-vite-config/pull/112) \([susnux](https://github.com/susnux)\)
* Updated dependencies:
* chore(deps): Bump vite-plugin-node-polyfills from 0.17.0 to 0.18.0 [\#89](https://github.com/nextcloud-libraries/nextcloud-vite-config/pull/89) \([dependabot](https://github.com/dependabot)\)
* chore(deps): Bump vite-plugin-css-injected-by-js from 3.3.0 to 3.3.1 [\#92](https://github.com/nextcloud-libraries/nextcloud-vite-config/pull/92) \([dependabot](https://github.com/dependabot)\)
* chore(deps): Bump …

chore: Prepare release 1.2.1

---

__tests__/appconfig.spec.ts
lib/appConfig.ts

When you import e.g. fonts in your scss like `url(some/font.woff)` the woff needs to be placed correctly, and especially the path needs to be set.
CSS does not allow dynamic URLs so we can not use our `OC.filepath` function but need to return a relative path to the CSS file that loaded the woff.

fix: Move fonts to `css/fonts` and fix css path resolving

---

__tests__/baseconfig.spec.ts
__tests__/libconfig.spec.ts
lib/baseConfig.ts
lib/libConfig.ts

If minify is disabled we need to not only not include the esbuild plugin but also set the option for vite to disable it.

fix(base): Correctly pass minify configuration to vite

---

CHANGELOG.md
package-lock.json
package.json

* chore: update source url in dep5 spec [\#187](https://github.com/nextcloud-libraries/nextcloud-vite-config/pull/187) \([st3iny](https://github.com/st3iny)\)
* chore(deps): Bump vite-plugin-node-polyfills from 0.21.0 to 0.22.0
* chore(deps): Bump @vitejs/plugin-vue from 5.0.4 to 5.0.5
* chore(deps): Bump @rollup/plugin-replace from 5.0.5 to 5.0.7

chore: Prepare v2.0.1 release

---

lib/appConfig.ts

(Production) bundles generated by vite break if the optimizer generates a `const` declaration that randomly has the name `OC`.
`Uncaught ReferenceError: can't access lexical declaration 'OC' before initialization`
> A lexical variable was accessed before it was initialized. This happens within any scope (global, module, function, or block) when variables declared with [let](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/let) or [const](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/const) are accessed before the place where they are declared has been executed.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Cant_access_lexical_declaration_before_init#what_went_wrong

fix: explicitly use window.OC global in app config

---

__tests__/appconfig.spec.ts
lib/appConfig.ts

Some apps use a different name in package.json than the real app ID is. But we need the app ID, so add an option to override it.

feat(app-config): Add option to override the app name

---

lib/appConfig.ts
lib/utils/appinfo.ts

1. Allow to set a custom prefix for assets instead of forcing `appName-`
2. Load app id from appinfo if possible

Allow to specify an output prefix and load app id from appinfo

---

LICENSES/MIT.txt
__fixtures__/css-entry-points/first.js
__fixtures__/css-entry-points/global.css
__fixtures__/css-entry-points/second.js
__fixtures__/css-entry-points/shared.css
__fixtures__/css-entry-points/shared.js
__tests__/css-entry-points.spec.ts
lib/appConfig.ts
lib/plugins/CSSEntryPoints.ts

With `cssCodeSplit` vite only inlines CSS in async chunks, but it does not properly create CSS files for synchronously imported CSS.
<del>
TODO:
* Create also CSS entries if there are no styles imported? Pro: Empty CSS is cachable and today there might be no styles but tomorrow there might be some -> make devs lives easier.
</del> (implemented)

feat: Add `CSSEntryPointsPlugin` to fix vite for creating one CSS entry per JS entry point

---

CHANGELOG.md
package-lock.json
package.json

* feat(app-config): Add option to override the app name [\#206](https://github.com/nextcloud-libraries/nextcloud-vite-config/pull/206) \([susnux](https://github.com/susnux)\)
* Allow to specify an output prefix and load app id from appinfo [\#209](https://github.com/nextcloud-libraries/nextcloud-vite-config/pull/209) \([susnux](https://github.com/susnux)\)
* feat: Add `CSSEntryPointsPlugin` to fix vite for creating one CSS entry per JS entry point [\#210](https://github.com/nextcloud-libraries/nextcloud-vite-config/pull/210) \([susnux](https://github.com/susnux)\)
* chore(deps-dev): Bump vite from 5.2.13 to 5.3.1

chore: Prepare v1.3.0

---

CHANGELOG.md
package-lock.json
package.json

* feat(app-config): Add option to override the app name [\#205](https://github.com/nextcloud-libraries/nextcloud-vite-config/pull/205) \([susnux](https://github.com/susnux)\)
* Allow to specify an output prefix and load app id from appinfo [\#207](https://github.com/nextcloud-libraries/nextcloud-vite-config/pull/207) \([susnux](https://github.com/susnux)\)
* feat: Add `CSSEntryPointsPlugin` to fix vite for creating one CSS entry per JS entry point [\#204](https://github.com/nextcloud-libraries/nextcloud-vite-config/pull/204) \([susnux](https://github.com/susnux)\)
* chore(deps-dev): Bump vite from 5.2.13 to 5.3.1
* chore(deps): Bump braces from 3.0.2 to 3.0.3

chore: Prepare 2.1.0

---

lib/appConfig.ts
lib/plugins/EmptyJSDir.ts

This is sometimes handy if you extract the CSS then also the `css/` directory should be cleared.

feat(EmptyJSDirPlugin): Allow to specify other directories to clear

---

__tests__/appconfig.spec.ts
lib/appConfig.ts

* Resolves #222 
If no CSS inline always add the CSS entry point plugin if not explicitly disabled `cssCodeSplit`.

fix(appconfig): `cssCodeSplit` is enabled by default so handle CSS entries

---

__tests__/css-entry-points.spec.ts
lib/appConfig.ts

Otherwise the browser cache is not refetching updated files.
I noticed after the upgrade on our instance today that the files app was having weired styles, only a force refresh helped. Not sure this has been exactly this issue, but as I talked with someone before (likely @susnux) I thought I'd open that PR.

fix: Revert chunkFileNames to include hash

---

lib/appConfig.ts
lib/plugins/REUSELicensesPlugin.ts
package-lock.json
package.json

This is a vite version of the plugin we use on Nextcloud server for Webpack to extract the license information.
(I still think it makes sense to externalize the plugins a bit a allow others to reuse them :sweat_smile: )

feat: Add REUSE license plugin to extract license information for built assets

---

CHANGELOG.md
package-lock.json
package.json

* [stable1] feat(EmptyJSDirPlugin): Allow to specify other directories to clear [\#242](https://github.com/nextcloud-libraries/nextcloud-vite-config/pull/242)
* [stable1] feat: Add REUSE license plugin to extract license information for built assets [\#276](https://github.com/nextcloud-libraries/nextcloud-vite-config/pull/276)
* [stable1] perf(CSSEntryPointsPlugin): Only visit chunks once per entry point [\#241](https://github.com/nextcloud-libraries/nextcloud-vite-config/pull/241)
* [stable1] fix(appconfig): `cssCodeSplit` is enabled by default so handle CSS entries [\#244](https://github.com/nextcloud-libraries/nextcloud-vite-config/pull/244)
* [stable1] fix: Revert chunkFileNames to include hash [\#275](https://github.com/nextcloud-libraries/nextcloud-vite-config/pull/275)
* [stable1] …

chore: Prepare release of v1.4.0

---

CHANGELOG.md
package-lock.json
package.json

* feat(EmptyJSDirPlugin): Allow to specify other directories to clear [\#240](https://github.com/nextcloud-libraries/nextcloud-vite-config/pull/240) \([susnux](https://github.com/susnux)\)
* feat: Add REUSE license plugin to extract license information for built assets [\#250](https://github.com/nextcloud-libraries/nextcloud-vite-config/pull/250) \([susnux](https://github.com/susnux)\)
* perf(CSSEntryPointsPlugin): Only visit chunks once per entry point [\#239](https://github.com/nextcloud-libraries/nextcloud-vite-config/pull/239) \([susnux](https://github.com/susnux)\)
* fix(appconfig): `cssCodeSplit` is enabled by default so handle CSS entries [\#243](https://github.com/nextcloud-libraries/nextcloud-vite-config/pull/243) \([susnux](https://github.com/susnux)\)
* fix: Revert …

chore: Prepare release of v2.2.0

---

lib/baseConfig.ts
package-lock.json
package.json

That subpath is no longer exported (or it is no longer accessible) in 1.1.2.

fix: Adjust import of `rollup-plugin-esbuild-minify`

---

lib/plugins/REUSELicensesPlugin.ts

Otherwise the files contain the hash placeholder, as the hash is only generated just before `generateBundle`. And Rollup does not replace the hash for other files, so we would end up with files like `foo-!{0001}.js.license`.
Tested with `files_downloadlimit`. Best review without whitespaces ;)

fix(REUSELicensesPlugin): Emit files in `generateBundle` hook to have real filenames

---

lib/plugins/REUSELicensesPlugin.ts

- `new Set()` of object array doesn't remove duplicates, because object with the same values still have different references
- Using `Map` with serialized key to remove duplicates

fix(REUSELicensesPlugin): remove duplicates in license files

---

CHANGELOG.md
package-lock.json
package.json

* Support for Vite 6
* Dropped support for Vite 4 as the vue plugin is no longer compatible with v4 and v6.
* fix(REUSELicensesPlugin): remove duplicates in license files [\#293](https://github.com/nextcloud-libraries/nextcloud-vite-config/pull/293) \([ShGKme](https://github.com/ShGKme)\)
* ci: Update dependabot-approve-merge.yml [\#315](https://github.com/nextcloud-libraries/nextcloud-vite-config/pull/315) \([AndyScherzinger](https://github.com/AndyScherzinger)\)
* chore(deps): Bump elliptic to 6.6.0
* chore(deps): Bump magic-string to 0.30.17
* chore(deps): Bump nanoid to 3.3.8
* chore(deps): Bump rollup-plugin-corejs to 1.0.1
* chore(deps): Bump rollup-plugin-esbuild-minify to 1.2.0
* chore(deps): Bump rollup-plugin-license to 3.5.3
* chore(deps): …

chore: Prepare release v2.3.0

---

CHANGELOG.md
package-lock.json
package.json

* Vite 6 support
* fix(REUSELicensesPlugin): remove duplicates in license files
* chore(deps): Bump magic-string from 0.30.15 to 0.30.17
* chore(deps): Bump rollup-plugin-corejs to 1.0.1
* chore(deps): Bump rollup-plugin-license to 3.5.3
* chore(deps): Bump rollup-plugin-esbuild-minify to 1.2.0
* chore(deps): Bump rollup-plugin-node-externals to 8.0.0
* chore(deps): Bump vite-plugin-css-injected-by-js to 3.5.2
* chore(deps): Bump vite-plugin-dts to 4.4.0
* chore(deps): Bump @vitejs/plugin-vue2 to 2.3.3
* chore(deps): Bump @rollup/plugin-replace to 6.0.2

chore: Prepare release v1.5.0

---

CHANGELOG.md
package-lock.json
package.json

* fix: Vite 6 made the CSS output file breaking [\#470](https://github.com/nextcloud-libraries/nextcloud-vite-config/pull/470)
* chore(deps): Bump vite-plugin-dts to 4.5.0

chore: Prepare v2.3.1

---

lib/appConfig.ts

* Resolves https://github.com/nextcloud-libraries/nextcloud-vite-config/security/code-scanning/3
CodeQL:
> Sanitizing untrusted input is a common technique for preventing injection attacks such as SQL injection or cross-site scripting. Usually, this is done by escaping meta-characters such as quotes in a domain-specific way so that they are treated as normal characters.

fix: Incomplete string escaping or encoding

---

CHANGELOG.md
package-lock.json
package.json

* chore(deps): Bump vite-plugin-node-polyfills from 0.22.0 to 0.23.0
* Required for vite 6 support

[stable1] chore: Prepare v1.5.2

---

__tests__/__snapshots__/appconfig.spec.ts.snap
lib/baseConfig.ts

I do not see a reason why we should hide source maps on production builds and it makes reading traces and debugging a lot harder on production setups.

fix: Do not hide sourcemaps in production build

---

CHANGELOG.md
package-lock.json
package.json

This release will resolve various GitHub security warning about GHSA GHSA-67mh-4wv8-2f99 in projects using this shared configuration.

chore: prepare v1.5.4

---

.github/release.yml
CHANGELOG.md
package-lock.json
package.json

This release will resolve various GitHub security warning about GHSA `GHSA-67mh-4wv8-2f99` in projects using this shared configuration.

chore: prepare release of v2.3.3

---

lib/plugins/REUSELicensesPlugin.ts

- fixes bundles that only contain virtual vite modules (e.g. common js helper).
- fix `file://` URL to path conversion

fix(SPDX): handle vite internal modules and sanitize name

---

CHANGELOG.md
README.md
build/format-changelog.mjs
package-lock.json
package.json

Add release documentation similar to nextcloud-vue and bump version.
---
* fix(SPDX): handle vite internal modules and sanitize name [\#606](https://github.com/nextcloud-libraries/nextcloud-vite-config/pull/606) \([susnux](https://github.com/susnux)\)
* chore(deps-dev): Bump vite to 6.3.4

chore: prepare v2.3.4

---

lib/baseConfig.ts
package-lock.json
package.json

- closes https://github.com/nextcloud-libraries/nextcloud-vite-config/pull/630
Otherwise it is not possible to have input and output in the same base dir.

fix(watch): adjust rollup config for watch mode

---

CHANGELOG.md
package-lock.json
package.json

* Minimum Vite version is now 7.1.4
* fix: bump vite version to fix running in watch mode [\#693](https://github.com/nextcloud-libraries/nextcloud-vite-config/pull/693) \([susnux](https://github.com/susnux)\)
* chore: update `vite-plugin-node-polyfills` to `0.24.0` [\#678](https://github.com/nextcloud-libraries/nextcloud-vite-config/pull/678) \([skjnldsv](https://github.com/skjnldsv)\)
* chore: various dev deps upgrades [\#680](https://github.com/nextcloud-libraries/nextcloud-vite-config/pull/680) \([skjnldsv](https://github.com/skjnldsv)\)
* chore(deps): Bump @vitejs/plugin-vue from 6.0.0 to 6.0.1 [\#681](https://github.com/nextcloud-libraries/nextcloud-vite-config/pull/681)
* chore(deps): Bump cipher-base from 1.0.4 to 1.0.6 [\#687](https://github.com/nextcloud-libraries/nextcloud-vite-c …

chore: prepare v2.5.0

---

CHANGELOG.md
package-lock.json
package.json

* fix: make configuration rolldown compatible [\#717](https://github.com/nextcloud-libraries/nextcloud-vite-config/pull/717) \([susnux](https://github.com/susnux)\)
* chore(deps): Bump rollup-plugin-node-externals to 8.1.1
* chore(deps): Bump magic-string to 0.30.19

chore: prepare v2.5.1

---

CHANGELOG.md
package-lock.json
package.json

* fix: make configuration rolldown compatible [\#718](https://github.com/nextcloud-libraries/nextcloud-vite-config/pull/718)
* chore(deps): Bump rollup-plugin-node-externals to 8.1.1
* chore(deps): Bump magic-string to 0.30.19

chore: prepare v1.7.1
